name: Build & Test

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * */2' # at 0:00 every two days

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
    - name: Cache pnpm modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
    - name: Find version
      run: |
        npm run env | grep npm_package_version >> $GITHUB_ENV
    - run: |
        echo Workflow triggered by event ${{ github.event_name }}
    
    - name: Build
      run: npm run build:all # does not run tests
      env:
        YT_API_KEY: ${{ secrets.YOUTUBE_KEY }}

    - name: Archive extension
      uses: actions/upload-artifact@v2
      with:
        name: enhancer_for_nebula-${{ env.npm_package_version }}
        path: |
          extension-dist/
        if-no-files-found: error
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
    - name: Cache pnpm modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
    - name: Find version
      run: |
        npm run env | grep npm_package_version >> $GITHUB_ENV
    
    - name: Get build files
      uses: actions/download-artifact@v2
      with:
        name: enhancer_for_nebula-${{ env.npm_package_version }}
        path: |
          extension-dist/
      
    # for headfull chrome
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Run all tests
      run: xvfb-run --auto-servernum npm run test -- --ci
      env:
        YT_API_KEY: ${{ secrets.YOUTUBE_KEY }}
        NEBULA_PASS: ${{ secrets.NEBULA_PASS }}
        NEBULA_USER: ${{ secrets.NEBULA_USER }}

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: build # only update coverage if build passes
    if: ${{ github.event_name != 'schedule' }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
    - name: Cache pnpm modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
      
    - name: Generate coverage
      run: npm run coverage
      env:
        YT_API_KEY: ${{ secrets.YOUTUBE_KEY }}
    - name: Upload coverage
      uses: codecov/codecov-action@v1
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
    - name: Cache pnpm modules
      uses: actions/cache@v2
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
        run_install: true
    - name: Find version
      run: |
        npm run env | grep npm_package_version >> $GITHUB_ENV
    
    - name: Get build files
      uses: actions/download-artifact@v2
      with:
        name: enhancer_for_nebula-${{ env.npm_package_version }}
        path: |
          extension-dist/
        
    - name: Package extension
      run: npx web-ext build

    - name: Push to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          web-ext-artifacts/enhancer_for_nebula-${{ env.npm_package_version }}.zip
        fail_on_unmatched_files: true
        draft: true
        name: Version ${{ env.npm_package_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
